name: RISC-V bare metal CI

on:
  push:
    branches:
      - '**'
  pull_request:

  schedule:
  - cron: "40 2 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
          sudo apt update --yes
          sudo apt install -o Acquire::Retries=3 --yes \
              git                     \
              gcc-riscv64-unknown-elf \
              qemu-system-misc        \
              opensbi                 \
              u-boot-qemu             \
              u-boot-tools
    - name: make
      run: make
    - name: print disassembly
      run: cat kernel/kleinix.asm
    - name: make run
      run: sh -c 'timeout 30s make run || true &' 2>&1 | tee output
    - name: check expected output
      run: |
          git grep --quiet --no-index --all-match \
              -e '^OpenSBI v[0-9]\+'     \
              -e '^U-Boot [0-9]\+'       \
              -e '^Starting kernel'      \
              -e '^Kleinix v[0-9]'       \
              -e '^cpu.\+: Hello World!' \
              -e '^cpu.\+: non_boot_cpu' \
              output
